// demo/maka/maka-react-1/src/components/desktop/desktop.tsx
import * as React from 'react';
import { connect } from "react-redux";
import { Dispatch } from 'redux';
import _ from 'underscore'

import './desktop.css'
import { CardState } from '../../interfaces/store';
import { cardResource } from '../../interfaces/model';
import { resourceCollect} from "../../store/action/resource";
import { pageAction } from '../../store/action/card';

interface desktopProp {
    pageid:string,
    resources:cardResource[],
    changeResOnCurrent?(pageid:string,id:string,cardRes:cardResource):pageAction,
    addResOnCurrent?(pageid:string,cardRes:cardResource):pageAction
}

interface editResourceItem {
    resource:cardResource
}
function EditResourceItem(props:editResourceItem){
    const oneResource = resourceCollect.get(props.resource.resourceid)
    let  [posStart,setPosStart] = React.useState({
        x:0,
        y:0
    })
    const [translate,setTranslate] = React.useState({
        x:0,
        y:0
    })
    function dragStartHandler(e:React.DragEvent<HTMLDivElement>){
        posStart = {
            x:e.pageX,
            y:e.pageY
        }
        e.dataTransfer.setData("text",JSON.stringify({id:props.resource.id,cardRId:props.resource.id,posStart}));
        e.dataTransfer.setData('type','self');
        e.dataTransfer.effectAllowed = "move";
    }
    function dragHandler(e:React.DragEvent<HTMLDivElement>){
        const left = e.pageX - posStart.x;
        const top = e.pageY - posStart.y;
        setTranslate({
            x:left,
            y:top
        })
    }
    function dragEndHandler(e:React.DragEvent<HTMLDivElement>){
        setTranslate({
            x:0,
            y:0
        })
    }
    return (
        <div className="resource-item" draggable="true" 
            key={props.resource.id} 
            onDragStart={dragStartHandler}
            onDrag={dragHandler}
            onDragEnd={dragEndHandler}
            style={{
                width:`${props.resource.width}px`,
                height:`${props.resource.height}px`,
                top:`${props.resource.position.y}px`,
                left:`${props.resource.position.x}px`,
                transform:`rotate(${props.resource.rotate}deg) translate(${translate.x}px,${translate.y}px)`
            }}
        >
            <img src={oneResource.url} alt="" />
            <span className="remove">✕</span>
        </div>
    )
}

function desktop(props:desktopProp){
    // let [resourceItem,setresourceItem] = React.useState([]);
    let [isdrop,setIsdrog]= React.useState(false);
    let setting ={
        width:375,
        height:667
    }
    const desk:any = React.useRef(null)
    // React.useEffect(()=>{
    //     setresourceItem(props.resources && props.resources.map(r => (
    //         <EditResourceItem resource={r} key={r.id}/>
    //     )))
    // },[props.resources])
    let resourceItem = props.resources && props.resources.map(r => (
        <EditResourceItem resource={r} key={r.id}/>
    ))
    function dragoverHandler(e:React.DragEvent<HTMLDivElement>){
        e.preventDefault();
        setIsdrog(true);
    }
    function dropHandler(e:React.DragEvent<HTMLDivElement>){
        setIsdrog(false);
        const rid:string = e.dataTransfer.getData("text");
        const type:string = e.dataTransfer.getData("type");
        const rdata:{
            id:string,
            cardRId:string,
            posStart:{
                x:number,
                y:number
            }
        } =  JSON.parse(rid);
        const top:number = e.pageY - desk.current.offsetTop;
        const left:number = e.pageX - desk.current.offsetLeft - setting.width / 2;
        const position = {
            x:left,
            y:top
        }
        if(type == 'self'){
            const rSetting:cardResource = _.find(props.resources,c => c.id == rdata.cardRId);
            rSetting.position.y += e.pageY - rdata.posStart.y;
            rSetting.position.x += e.pageX - rdata.posStart.x;
            props.changeResOnCurrent(props.pageid,rdata.cardRId,rSetting)
        }else{
            const cardRId:string = Math.random().toString(36).substr(2);
            const cardSetting:cardResource = {
                id:cardRId,
                resourceid:rdata.id,
                position,
                rotate:0,
                width:setting.width,
                height:null,
                zIndex:1
            }
            props.addResOnCurrent(props.pageid,cardSetting)
        }
    }
    return (
        <div className="desktop" onDragOver={dragoverHandler} onDrop={dropHandler} ref={desk}>
            <div className="drophere" 
                style={isdrop?{display:'flex'}:{display:'none'}}
            >拖放到这里</div>
            <div className="desktop-box">
                { resourceItem }
            </div>
        </div>
    )
}

const mapStateToProps = (state: CardState): { pageid:string,resources: cardResource[]} => ({
    pageid:state.pageid,
    resources:state.currentPage && state.currentPage.resourseList
})

// 将 对应action 插入到组件的 props 中
const mapDispatchToProps = (dispatch: Dispatch,ownProps) => ({
    changeResOnCurrent:(pageid:string,id:string,cardRes:cardResource) => dispatch({type:'changeOneRes',crid:id,crdata:cardRes,page:pageid}),
    addResOnCurrent:(pageid:string,cardRes:cardResource) =>dispatch({type:'addRes',crdata:cardRes,page:pageid})
})

const desktopCom = connect(mapStateToProps, mapDispatchToProps)(desktop);

export default desktopCom;

export {
    desktop
}

// demo/maka/maka-vue/src/components/desktop.vue
<template>
    <div class="desktop" @dragover="ondragover($event)"  @drop="ondrop($event)" ref="desk" :style="sizestyle">
        <div class="drophere" v-show="showHere">拖放到这里</div>
        <div class="desktop-box" v-if="contentPage">
            <editResourceItem 
                v-for="resource in contentPage.resourseList" 
                :key="resource.id" 
                :resource = "resource"
                :dragable = "dragable"
            ></editResourceItem>
        </div>
    </div>
</template>

<script lang="ts">
import { Component, Vue,Prop } from 'vue-property-decorator';
import { Action, Mutation, Getter, State,namespace } from 'vuex-class';
import _ from 'underscore';

import { CardModel } from '../models/card'
import { cardResource } from '../interfaces/model'

import editResourceItem from './editresourceitem.vue'



const cardModule = namespace('card')


@Component({
    components:{
        editResourceItem
    }
})
export default class DeskTop extends Vue {
    @cardModule.Mutation('addResOnCurrent') addResOnCurrent!:Function;
    @cardModule.Mutation('changeResOnCurrent') changeResOnCurrent!:Function;

    @Prop() contentPage:CardModel;
    @Prop() dragable:boolean;

    showHere:boolean = false;
    setting = {
        width:375,
        height:667
    }
    get sizestyle(){
        return `width:${this.setting.width}px;height:${this.setting.height}px`
    }
    ondragover(e:DragEvent){
        e.preventDefault();
        this.showHere = true;
    }
    
    ondrop(e:DragEvent){
        this.showHere = false;
        const rid:string = e.dataTransfer.getData("text");
        const type:string = e.dataTransfer.getData("type");
        const rdata:{
            id:string,
            cardRId:string,
            posStart:{
                x:number,
                y:number
            }
        } =  JSON.parse(rid);
        const desk:any = this.$refs.desk;
        const top:number = e.pageY - desk.offsetTop;
        const left:number = e.pageX - desk.offsetLeft - this.setting.width / 2;
        const position = {
            x:left,
            y:top
        }
        if(type == 'self'){
            const rSetting:cardResource = _.find(this.contentPage.resourseList,c => c.id == rdata.cardRId);
            rSetting.position.y += e.pageY - rdata.posStart.y;
            rSetting.position.x += e.pageX - rdata.posStart.x;
            this.changeResOnCurrent({
                id:rdata.cardRId,
                cardRes:rSetting
            })
        }else{
            const cardRId:string = Math.random().toString(36).substr(2);
            const cardSetting:cardResource = {
                id:cardRId,
                resourceid:rdata.id,
                position,
                rotate:0,
                width:this.setting.width,
                height:null,
                zIndex:1
            }
            this.addResOnCurrent(cardSetting)
        }
    }
    
}
</script>
<style scoped>
.desktop{
    box-shadow: 0 0 10px #aaa;
    background: #fff;
    margin: auto;
    position: relative;
}
.drophere{
    display: flex;
    position: absolute;
    top: 0;
    left: 0;
    border: 1px dashed;
    width: 100%;
    height: 100%;
    background: rgba(255,255,255,.3);
    justify-content: center;
    align-items: center;
    font-size: 1.5rem;
    z-index: 1000;
    pointer-events: none;
}

</style>
