// demo/maka/maka-vue/src/components/avatar.vue
<template>
    <div class="g-avatar">
        <img :src="avatar">`
    </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { Action, Mutation, Getter, State,namespace } from 'vuex-class';
import {UserModel} from '../models/user'

const userModule = namespace('user')

@Component
export default class Avatar extends Vue {
    @userModule.State('currentUser') currentUser:UserModel
    get avatar():string{
        return this.currentUser.getavatar();
    }
}
</script>

// demo/maka/maka-react-1/src/components/avatar/avatar.tsx
import * as React from 'react';
import { connect } from "react-redux";
import { Dispatch } from 'redux';

import { UserModel } from "../../models/user";
import { setCurrentUser, setUserAction } from "../../store/action/user"
import { UserState } from "../../interfaces/store"

interface AvaProps {
    currentUser:UserModel,
    setCurrentUser(id:string):setUserAction
}
function Avatar(props:AvaProps){
    
    // React.useEffect(()=>{
    //     console.log(props)
    // },[])
    return (
        <div className="g-avatar">
            <img src={props.currentUser.avatar}/>
        </div>
    )
}

const mapStateToProps = (state: UserState): { currentUser: UserModel } => ({
    currentUser:state.currentUser
})

// 将 对应action 插入到组件的 props 中
const mapDispatchToProps = (dispatch: Dispatch,ownProps) => ({
    setCurrentUser: () => dispatch(setCurrentUser(ownProps.id)),
})

const AvatarCom = connect(mapStateToProps, mapDispatchToProps)(Avatar);
export default AvatarCom;
